/**
 * Copyright © 2017-2026, Galactic-Shrine - All Rights Reserved.
 * Copyright © 2017-2026, Galactic-Shrine - Tous droits réservés.
 * 
 * Mozilla Public License 2.0 / Licence Publique Mozilla 2.0
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
 * Modifications to this file must be shared under the same Mozilla Public License, v. 2.0.
 *
 * Cette Forme de Code Source est soumise aux termes de la Licence Publique Mozilla, version 2.0.
 * Si une copie de la MPL ne vous a pas été distribuée avec ce fichier, vous pouvez en obtenir une à l'adresse suivante : https://mozilla.org/MPL/2.0/.
 * Les modifications apportées à ce fichier doivent être partagées sous la même Licence Publique Mozilla, v. 2.0.
 **/

//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalacticShrine.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalacticShrine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Algorithme de hachage non implémenté..
        /// </summary>
        public static string AlgorithmeHachageNonImplemente {
            get {
                return ResourceManager.GetString("AlgorithmeHachageNonImplemente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AVERTISSEMENT.
        /// </summary>
        public static string AVERTISSEMENT {
            get {
                return ResourceManager.GetString("AVERTISSEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le chemin ou le nom du fichier journal n&apos;est pas défini..
        /// </summary>
        public static string CheminOuNomDuJournalPasDefini {
            get {
                return ResourceManager.GetString("CheminOuNomDuJournalPasDefini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ah mes yeux ! Pourquoi cette console est trop petite ?.
        /// </summary>
        public static string ConsoleEstTropPetite {
            get {
                return ResourceManager.GetString("ConsoleEstTropPetite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création d&apos;une archive à {0}....
        /// </summary>
        public static string CreationDArchive {
            get {
                return ResourceManager.GetString("CreationDArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création de l&apos;archive terminée..
        /// </summary>
        public static string CreationDArchiveTerminee {
            get {
                return ResourceManager.GetString("CreationDArchiveTerminee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ERREUR.
        /// </summary>
        public static string ERREUR {
            get {
                return ResourceManager.GetString("ERREUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de connexion au serveur : {0}.
        /// </summary>
        public static string ErreurConnexionServeur {
            get {
                return ResourceManager.GetString("ErreurConnexionServeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de somme de contrôle pour le fichier {0}. L&apos;extraction a été interrompue..
        /// </summary>
        public static string ErreurGsPDeSomme {
            get {
                return ResourceManager.GetString("ErreurGsPDeSomme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extraction de l&apos;archive de {0}....
        /// </summary>
        public static string ExtractionDArchive {
            get {
                return ResourceManager.GetString("ExtractionDArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extraction terminée..
        /// </summary>
        public static string ExtractionTerminee {
            get {
                return ResourceManager.GetString("ExtractionTerminee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier ajouté : {0} (taille originale : {1} octets)..
        /// </summary>
        public static string FichierAjouteGsP {
            get {
                return ResourceManager.GetString("FichierAjouteGsP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier extrait : {0}..
        /// </summary>
        public static string FichierExtrait {
            get {
                return ResourceManager.GetString("FichierExtrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier GSP non valide..
        /// </summary>
        public static string FichierGspInvalide {
            get {
                return ResourceManager.GetString("FichierGspInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les noms de fichiers ne peuvent pas être terminés par un caractère de séparation de chemin d&apos;accès..
        /// </summary>
        public static string FichierTermineInvalide {
            get {
                return ResourceManager.GetString("FichierTermineInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier trouvé : {0}..
        /// </summary>
        public static string FichierTrouve {
            get {
                return ResourceManager.GetString("FichierTrouve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à INFO.
        /// </summary>
        public static string INFO {
            get {
                return ResourceManager.GetString("INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initialisation de l&apos;archive..
        /// </summary>
        public static string InitArchive {
            get {
                return ResourceManager.GetString("InitArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;argument.
        /// </summary>
        public static string LArgument {
            get {
                return ResourceManager.GetString("LArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le chemin ne peut pas être vide..
        /// </summary>
        public static string LeCheminNePeutPasEtreVide {
            get {
                return ResourceManager.GetString("LeCheminNePeutPasEtreVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le message ne peut pas être vide..
        /// </summary>
        public static string LeMessageNePeutPasEtreVide {
            get {
                return ResourceManager.GetString("LeMessageNePeutPasEtreVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom de la variable d&apos;environnement ne peut pas être vide..
        /// </summary>
        public static string LeNomDeLaVariableDEnvironnementNePeutPasEtreVide {
            get {
                return ResourceManager.GetString("LeNomDeLaVariableDEnvironnementNePeutPasEtreVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom du fichier ne peut pas être vide..
        /// </summary>
        public static string LeNomDuFichierNePeutPasEtreVide {
            get {
                return ResourceManager.GetString("LeNomDuFichierNePeutPasEtreVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le paramètre `{0}` ne peut pas être vide..
        /// </summary>
        public static string LeParametreNePeutPasEtreVide {
            get {
                return ResourceManager.GetString("LeParametreNePeutPasEtreVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des fichiers dans l&apos;archive {0}....
        /// </summary>
        public static string ListeDesFichiersDansLArchive {
            get {
                return ResourceManager.GetString("ListeDesFichiersDansLArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accès non autorisé à la ressource demandée..
        /// </summary>
        public static string MessageExceptionAccesNonAutoriseALaRessourceDemandee {
            get {
                return ResourceManager.GetString("MessageExceptionAccesNonAutoriseALaRessourceDemandee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;argument est hors des limites autorisées..
        /// </summary>
        public static string MessageExceptionArgumentEstHorsDesLimitesAutorisees {
            get {
                return ResourceManager.GetString("MessageExceptionArgumentEstHorsDesLimitesAutorisees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;argument fourni est invalide..
        /// </summary>
        public static string MessageExceptionArgumentFourniEstInvalide {
            get {
                return ResourceManager.GetString("MessageExceptionArgumentFourniEstInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette fonctionnalité n&apos;est pas supportée..
        /// </summary>
        public static string MessageExceptionCetteFonctionnaliteNEstPasSupportee {
            get {
                return ResourceManager.GetString("MessageExceptionCetteFonctionnaliteNEstPasSupportee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;argument &apos;{0}&apos;.
        /// </summary>
        public static string MessageExceptionLArgumentAvecVars {
            get {
                return ResourceManager.GetString("MessageExceptionLArgumentAvecVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La validation a échoué..
        /// </summary>
        public static string MessageExceptionLaValidationAEchoue {
            get {
                return ResourceManager.GetString("MessageExceptionLaValidationAEchoue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le chemin spécifié est trop long..
        /// </summary>
        public static string MessageExceptionLeCheminSpecifieEstTropLong {
            get {
                return ResourceManager.GetString("MessageExceptionLeCheminSpecifieEstTropLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier est introuvable..
        /// </summary>
        public static string MessageExceptionLeFichierEstIntrouvable {
            get {
                return ResourceManager.GetString("MessageExceptionLeFichierEstIntrouvable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format du GsId est invalide..
        /// </summary>
        public static string MessageExceptionLeFormatDuGsIdEstInvalide {
            get {
                return ResourceManager.GetString("MessageExceptionLeFormatDuGsIdEstInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format fourni est invalide..
        /// </summary>
        public static string MessageExceptionLeFormatFourniEstInvalide {
            get {
                return ResourceManager.GetString("MessageExceptionLeFormatFourniEstInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;opération demandée n&apos;est pas valide..
        /// </summary>
        public static string MessageExceptionLOperationDemandeeNEstPasValide {
            get {
                return ResourceManager.GetString("MessageExceptionLOperationDemandeeNEstPasValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} possède une valeur hors des limites autorisées. Valeur actuelle : &apos;{1}&apos;..
        /// </summary>
        public static string MessageExceptionParamsPossedeUneValeurHorsDesLimitesAutoriseesValeurActuelleAvecVars {
            get {
                return ResourceManager.GetString("MessageExceptionParamsPossedeUneValeurHorsDesLimitesAutoriseesValeurActuelleAvecV" +
                        "ars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} possède une valeur hors limites. Valeur actuelle : &apos;{1}&apos;. Limites autorisées : [{2} ; {3}]..
        /// </summary>
        public static string MessageExceptionParamsPossedeUneValeurHorsLimitesValeurActuelleLimitesAutoriseesAvecVars {
            get {
                return ResourceManager.GetString("MessageExceptionParamsPossedeUneValeurHorsLimitesValeurActuelleLimitesAutoriseesA" +
                        "vecVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} possède une valeur non prise en charge. Valeur actuelle : &apos;{1}&apos;..
        /// </summary>
        public static string MessageExceptionParamsPossedeUneValeurNonPriseEnChargeValeurActuelleAvecVars {
            get {
                return ResourceManager.GetString("MessageExceptionParamsPossedeUneValeurNonPriseEnChargeValeurActuelleAvecVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} possède une valeur non prise en charge. Valeur actuelle : &apos;{1}&apos;. Valeurs autorisées : {2}..
        /// </summary>
        public static string MessageExceptionParamsPossedeUneValeurNonPriseEnChargeValeurActuelleValeursAutoriseesAvecVars {
            get {
                return ResourceManager.GetString("MessageExceptionParamsPossedeUneValeurNonPriseEnChargeValeurActuelleValeursAutori" +
                        "seesAvecVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur de cryptage s&apos;est produite..
        /// </summary>
        public static string MessageExceptionUneErreurDeCryptageSEstProduite {
            get {
                return ResourceManager.GetString("MessageExceptionUneErreurDeCryptageSEstProduite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur Galactic-Shrine s&apos;est produite..
        /// </summary>
        public static string MessageExceptionUneErreurGalacticShrineSEstProduite {
            get {
                return ResourceManager.GetString("MessageExceptionUneErreurGalacticShrineSEstProduite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non concordance de la somme de contrôle..
        /// </summary>
        public static string NonConcordanceDeLaSommeDeControle {
            get {
                return ResourceManager.GetString("NonConcordanceDeLaSommeDeControle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fragment de chemin d&apos;accès &apos;{0}&apos; contient des séparateurs de répertoire invalides..
        /// </summary>
        public static string RepertoiresSeparateursInvalides {
            get {
                return ResourceManager.GetString("RepertoiresSeparateursInvalides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le serveur est en ligne..
        /// </summary>
        public static string ServeurEnLigne {
            get {
                return ResourceManager.GetString("ServeurEnLigne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le serveur est hors ligne..
        /// </summary>
        public static string ServeurHorsLigne {
            get {
                return ResourceManager.GetString("ServeurHorsLigne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signature d&apos;archive invalide..
        /// </summary>
        public static string SignatureDArchiveInvalide {
            get {
                return ResourceManager.GetString("SignatureDArchiveInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SUCCÉS.
        /// </summary>
        public static string SUCCES {
            get {
                return ResourceManager.GetString("SUCCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La longueur de la clé de chiffrement non valide. La clé de chiffrement doit être de 32 octets..
        /// </summary>
        public static string TailleDeCleInvalide {
            get {
                return ResourceManager.GetString("TailleDeCleInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version GsP non prise en charge : {0}..
        /// </summary>
        public static string VersionGsPNonSupportee {
            get {
                return ResourceManager.GetString("VersionGsPNonSupportee", resourceCulture);
            }
        }
    }
}
